#!/bin/sh

create_directories () {
    DIRS="workspace
    local
    programs
    sources"

    for DIR in $DIRS; do
        if [ ! -d "$DIR" ]; then
            mkdir "$DIR"
        fi
    done
}

create_symlinks () {
    cp ~/.repos/home-config/gitconfig{.sample,}

    ln -s ~/.repos/home-config/update-git-repos ~/.repos/update-git-repos
    ln -s ~/.repos/home-config/gitconfig .gitconfig
    ln -s ~/.repos/home-config/tmux.conf .tmux.conf
    ln -s ~/.repos/home-config/tmuxp .tmuxp
    ln -s ~/.repos/zsh-config/zshrc .zshrc
    ln -s ~/.repos/zsh-config/zshenv .zshenv
}

install_packages () {
    sudo apt install zsh tmux aptitude
    sudo apt install build-essential git tig cmake cmake-curses-gui

    mkdir -p ~/.tmux/plugins
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    exit
}

install_python () {
    cd ~/programs
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
}


cd ~/.repos
git clone https://github.com/zsh-users/antigen.git antigen
git clone https://github.com/WestFlame/zsh-config.git
git clone https://github.com/powerline/fonts.git powerline-fonts
git clone https://github.com/altercation/solarized
git clone https://github.com/Anthony25/gnome-terminal-colors-solarized.git
git clone https://github.com/jkaving/intellij-colors-solarized.git

cd powerline-fonts; ./install.sh; cd ..

cd ~
create_directories
create_symlinks

install_packages
