#!/bin/sh

create_directories () {
    DIRS="workspace
    local
    programs
    sources"

    for DIR in $DIRS; do
        if [ ! -d "$DIR" ]; then
            mkdir "$DIR"
        fi
    done
}

create_symlinks () {
    ln -s ~/.repos/home-config/gitconfig .gitconfig
    ln -s ~/.repos/home-config/tmux.conf .tmux.conf
    ln -s ~/.repos/zsh-antigen/zshrc .zshrc
}

install_packages () {
    su -
    apt-get install aptitude
    aptitude install zsh tmux
    aptitude install build-essential git cmake cmake-curses-gui
    aptitude install python3 python3-pip python3-numpy

    aptitude install libyaml-dev
    pip3 install tmuxp
    exit
}

cd ~/.repos
git clone --recursive git@github.com:WestFlame/zsh-antigen.git
git clone https://github.com/powerline/fonts powerline-fonts

cd powerline-fonts; ./install.sh; cd ..

cd ~
create_directories
create_symlinks

install_packages
